import type { BadgeTone } from "../components/ui/Badge";

const statusToneMap: Record<string, BadgeTone> = {
  Available: "green",
  Reserved: "amber",
  Sold: "slate",
  Blocked: "red",
  Unavailable: "red",
  New: "blue",
  "Pending Review": "amber",
  "In Review": "blue",
  "Missing Info": "amber",
  "Missing Information": "amber",
  Approved: "green",
  Rejected: "red",
  Declined: "red",
  "New Lead": "blue",
  Contacted: "blue",
  Interested: "green",
  "Family Decision": "amber",
  "Site Visit Scheduled": "blue",
  "Deposit Pending": "amber",
  "Deposit Paid": "green",
  "Payment Plan Review": "amber",
  Draft: "gray",
  "Deposit Submitted": "blue",
  "Deposit Confirmed": "green",
  "Converted to Application": "green",
  "Converted to Contract": "green",
  Expired: "amber",
  Cancelled: "gray",
  Released: "gray",
  "Not Requested": "gray",
  Pending: "amber",
  "Proof Submitted": "blue",
  Confirmed: "green",
  Waived: "brown",
  "Not Started": "gray",
  "In Progress": "blue",
  Drafting: "blue",
  "Ready For Review": "amber",
  "Sent For Signature": "blue",
  Signed: "green",
  "Missing Documents": "amber",
  Complete: "green",
  Ready: "amber",
  "Handed Off": "green",
  Active: "green",
  "Contract Started": "blue",
  "Closed/Won": "green",
  "Lost/Inactive": "gray",
  Current: "green",
  "Due Soon": "amber",
  Overdue: "red",
  "Missing Proof": "amber",
  Completed: "green",
  Missing: "amber",
  Uploaded: "blue",
};

export function statusBadgeTone(status: string | null | undefined): BadgeTone {
  if (!status) return "gray";
  return statusToneMap[status] ?? "gray";
}
