-- AI-assisted application summaries and completeness reviews.

create table if not exists public.application_ai_reviews (
  id bigint generated always as identity primary key,
  application_id bigint not null unique references public.applications(id) on delete cascade,
  summary text not null,
  completeness_status text not null,
  missing_fields jsonb not null default '[]'::jsonb,
  risk_flags jsonb not null default '[]'::jsonb,
  recommended_admin_actions jsonb not null default '[]'::jsonb,
  model text not null,
  generated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint application_ai_reviews_status_valid check (
    completeness_status in ('Complete', 'Needs Review', 'Missing Information', 'Lot Conflict')
  ),
  constraint application_ai_reviews_missing_fields_array check (jsonb_typeof(missing_fields) = 'array'),
  constraint application_ai_reviews_risk_flags_array check (jsonb_typeof(risk_flags) = 'array'),
  constraint application_ai_reviews_actions_array check (jsonb_typeof(recommended_admin_actions) = 'array')
);

create index if not exists idx_application_ai_reviews_application_id on public.application_ai_reviews(application_id);
create index if not exists idx_application_ai_reviews_status on public.application_ai_reviews(completeness_status);

drop trigger if exists trg_application_ai_reviews_updated_at on public.application_ai_reviews;
create trigger trg_application_ai_reviews_updated_at
before update on public.application_ai_reviews
for each row execute function public.set_updated_at();

alter table public.application_ai_reviews enable row level security;

drop policy if exists "Internal can read application AI reviews" on public.application_ai_reviews;
drop policy if exists "Admins manage application AI reviews" on public.application_ai_reviews;

create policy "Internal can read application AI reviews"
on public.application_ai_reviews
for select
using (public.is_internal_user());

create policy "Admins manage application AI reviews"
on public.application_ai_reviews
for all
using (public.is_admin_user())
with check (public.is_admin_user());

grant select, insert, update, delete on public.application_ai_reviews to authenticated;

comment on table public.application_ai_reviews is 'Read-only admin guidance generated by deterministic checks and optional Gemini summarization. It must not drive automatic approval decisions.';
